# Site settings
title: In Development
header-img: img/home-bg.png
email: thompson.julia@gmail.com
copyright_name: jmtho
description: > # this means to ignore newlines until "baseurl:"
  My journey through the Flatiron School Online Web Development Program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jmtho
learn_profile: jmtho
email_username: thompson.julia@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
